# .github/workflows/publish.yml
name: Build and Publish Python Package

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to read repo contents

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No API token needed!
          skip-existing: true  # Optional: skips if version already exists on PyPI
